name: gizzbrain
channels:
  - conda-forge
  - defaults
dependencies:
  # Base Python & Package Managers
  - python=3.11
  - pip
  
  # Development & Notebook Tools
  - ipykernel
  - jupyter
  
  # Data Processing & Audio Extraction
  - mutagen
  - pandas
  - numpy
  - pyarrow
  - librosa
  - tqdm